version: '3.8'
services:
  y-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321123566
      POSTGRES_DB: TOPSECRETPROJECT
    networks:
      - oursocialmediasite
networks:
  oursocialmediasite: